; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[colors][version] = "1.0-beta2"

projects[fullcalendar][version] = "2.0-beta3"

projects[superfish][version] = "1.8"

projects[views_bulk_operations][version] = "3.0-rc1"

projects[ctools][version] = "1.0"

projects[conditional_fields][version] = "3.x-dev"

projects[context][version] = "3.0-beta3"

projects[date][version] = "2.5"

projects[ds][version] = "1.5"

projects[entity][version] = "1.0-rc3"

projects[entityreference][version] = "1.0-rc3"

projects[features][version] = "1.0-rc3"

projects[field_group][version] = "1.1"

; Libraries
libraries[fullcalendar][download][type] = "get"
libraries[fullcalendar][download][url] = "http://arshaw.com/fullcalendar/downloads/fullcalendar-1.5.3.zip"
libraries[fullcalendar][directory_name] = "fullcalendar"
libraries[fullcalendar][type] = "library"
libraries[fullcalendar][download][subtree] = "fullcalendar"

; Modules
projects[libraries][version] = "1.0"

projects[masquerade][version] = "1.0-rc4"

projects[pathauto][version] = "1.1"

projects[registration][version] = "1.0-beta2"

projects[simple_gmap][version] = "1.0-rc1"

projects[strongarm][version] = "2.0"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = "git"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal.git"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

libraries[fullcalendar][download][type] = "get"
libraries[fullcalendar][download][url] = "http://arshaw.com/fullcalendar/downloads/fullcalendar-1.5.3.zip"
libraries[fullcalendar][download][subtree] = "fullcalendar"



; Modules
projects[token][version] = "1.1"

projects[views][version] = "3.3"

; Themes
projects[adaptivetheme][version] = "2.3"

projects[corolla][version] = "2.2"

projects[footheme][version] = "2.0"

; Libraries
libraries[tinymce][download][type] = "get"
libraries[tinymce][download][url] = "http://github.com/downloads/tinymce/tinymce/tinymce_3.5.4.1.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

