<?php

/**
 * Example theme hook implemented as a function. The base name of this file
 * (HOOK.func.inc) and the HOOK in the name of this function can be any
 * theming hook.
 *
 * When overriding an existing theming hook, make sure the required parameters
 * are set. This information can be found in the Drupal API documentation site
 * for core theming hooks. (http://api.drupal.org/api)
 * 
 * For contrib modules, the source code can be referred to.
 * 
 * @see http://drupal.org/node/173880
 *  More information on theme overrides.
 *
 * @see OWNER.theme.inc
 *  Where this function can also reside.
 */
function hex_starter_HOOK($arguments) {
  
}
