<?php

/**
 * This file can be used to hold a collection of theme functions and variable
 * processors grouped by their original creators.
 *
 * For example, the following hooks are defined by the core book module.
 * - book_navigation
 * - book_export_html
 * - book_title_link
 * - book_all_books_block
 * - book_node_export_html
 *
 * All the functions associated with the theming hooks listed above can live
 * in a single file named "book.theme.inc".
 *
 * This can apply for any module, theme or plug-in. Anything that defines its
 * own theming hook through HOOK_theme will be the parent owner of the
 * collection of theming hooks.
 *
 * @see http://api.drupal.org/api/search/7/HOOK_theme
 */
